services:
  db:
    container_name: trip-planner-db
    image: mysql:8.0
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=tripplanner
    ports:
      - "3306:3306"

  backend:
    container_name: trip-planner-backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend
      - ../frontend/dist:/var/www/frontend/dist
    depends_on:
      - db

  frontend:
    container_name: trip-planner-frontend
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/var/www/frontend
    depends_on:
      - db

  nginx:
    container_name: trip-planner-nginx
    image: nginx:latest
    environment:
      TZ: 'Azia/Tokyo'
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
